// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lfmyjpnelfvpgdhfojwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxmbXlqcG5lbGZ2cGdkaGZvand0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2MDg1NjYsImV4cCI6MjA4MDE4NDU2Nn0.qRce5_MbxUTGo6eQpW2Q_dtdUdun_F3RLJMoHcutCS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);