// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Read Supabase connection info from environment variables to make it easy
// to switch projects/databases without editing source code.
// In Vite, use VITE_ prefixed variables. If they're not set, we fall back to
// the new project values.
export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://hwnpbduxbaegnvadujck.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY ?? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3bnBiZHV4YmFlZ252YWR1amNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2OTIzNjMsImV4cCI6MjA4MDI2ODM2M30.naDMeD0W6FqCxa68Ab-zN3zKM6NULjidpaUvMXvuyQc";

// Import the supabase client like this:
// import { supabase, SUPABASE_URL } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);